<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

  <!-- Definer materialer -->
  <material name="black">
    <color rgba="0 0 0 1"/>
  </material>

  <material name="red">
    <color rgba="1 0 0 1"/>
  </material>

  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>

	<xacro:macro name="qube" params="stator_size:=0.102
  rotor_radius=0.025
  rotor_length=0.01
  angle_box_x=0.025
  angle_box_y:=0.002
  angle_box_z:=0.002">

    <!-- Links og joints -->
    <link name="base_link"/>

    <!-- Stator -->
    <link name="stator_link">
      <visual>
        <geometry>
          <box size="${stator_size} ${stator_size} ${stator_size}"/>
        </geometry>
        <material name="black"/>
      </visual>
    </link>

    <joint name="stator_joint" type="fixed">
      <parent link="base_link"/>
      <child link="stator_link"/>
      <origin xyz="0 0 ${stator_size/2}" rpy="0 0 0"/>
    </joint>

    <!-- Rotor -->
    <link name="rotor_link">
      <visual>
        <geometry>
          <cylinder radius="${rotor_radius}" length="${rotor_length}"/>
        </geometry>
        <material name="red"/>
      </visual>
    </link>

    <joint name="motor_joint" type="continuous">
      <parent link="stator_link"/>
      <child link="rotor_link"/>
      <origin xyz="0 0 ${stator_size/2 + rotor_length/2}" rpy="0 0 0"/>
      <axis xyz="0 0 -1"/>
    </joint>

    <!-- Vinkel-indikator -->
    <link name="angle_link">
      <visual>
        <geometry>
          <box size="${angle_box_x} ${angle_box_y} ${angle_box_z}"/>
        </geometry>
        <material name="white"/>
      </visual>
    </link>

    <joint name="indicator" type="fixed">
      <parent link="rotor_link"/>
      <child link="angle_link"/>
      <origin xyz="${angle_box_x/2} 0 ${rotor_length/2}" rpy="0 0 0"/>
    </joint>
	</xacro:macro>
</robot>